[package]
name = "albus"
version = "2.1.0"
edition = "2021"
authors = ["oqullcan"]
description = "Pure Rust DPI bypass and encrypted DNS tool for Linux"
license = "GPL-3.0-only"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.40", features = ["full"] }
reqwest = { version = "0.13", default-features = false, features = ["rustls", "http2"] }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs", "tls12"] }
url = "2.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
webpki-roots = "1.0"
hpke = "0.14.0"
hkdf = "0.13.0"
sha2 = "0.11.0"
chacha20poly1305 = "0.11.0"

[build-dependencies]
cc = "1.1"

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
