//! encrypted dns-over-https (doh) subsystem, in-memory wire cache, and resolv.conf manager.

pub mod allowlist;
pub mod anonymized_doh;
pub mod balancer;
pub mod benchmark;
pub mod blind_token;
pub mod blocklist;
pub mod blocklist_generator;
pub mod cache;
pub mod captive;
pub mod cloak;
pub mod client_rules;
pub mod diagnostics;
pub mod dns64;
pub mod dnscrypt_client;
pub mod dnssec;
pub mod doh;
pub mod dot;
pub mod doq;
pub mod ech;
pub mod ecs;
pub mod entropy;
pub mod filter;
pub mod forward;
pub mod ip_filter;
pub mod ipcrypt;
pub mod ipcrypt_batch;
pub mod local_doh;
pub mod local_dot;
pub mod logger;
pub mod metrics_server;
pub mod multipath;
pub mod netmon;
pub mod netprobe;
pub mod noise;
pub mod odoh;
pub mod padding;
pub mod pattern;
pub mod quic_migration;
pub mod schedule;
pub mod safesearch;
pub mod secure_mem;
pub mod server;
pub mod simd_crypto;
pub mod sources;
pub mod sphinx;
pub mod ssrf;
pub mod stamp;
pub mod stats;
pub mod stego;
pub mod system;
pub mod tcp;
pub mod tls_auth;
pub mod udp_pool;
pub mod uncloak;
pub mod watcher;
pub mod web_ui;
pub mod zkp_auth;

pub use allowlist::DomainAllowlist;
pub use anonymized_doh::{AnonymizedDoHClient, scrub_identifying_headers};
pub use benchmark::{run_benchmark, BenchmarkOptions, BenchmarkResult};
pub use blind_token::{RedemptionToken, TokenChallenge, TokenType};
pub use captive::CaptiveMap;
pub use blocklist::{build_seed_blocklist, fetch_and_compile_hagezi, CompactBlocklist};
pub use blocklist_generator::compile_blocklist;
pub use cloak::CloakEngine;
pub use client_rules::{ClientDecision, ClientProfile, ClientProfileConfig, ClientRuleEngine};
pub use dnscrypt_client::{AnonymizedRelay, DnsCryptCert, DnsCryptClient};
pub use entropy::{fill_dual_entropy, generate_key_32, generate_nonce_12, generate_nonce_24};
pub use dnssec::{
    check_anti_downgrade, inspect_response_dnssec, DnssecAlgorithm, DnssecReport, DowngradeViolation,
    RootTrustAnchor,
};
pub use doh::{extract_upstream_ips, extract_upstream_ips_v6};
pub use dot::{DotClient, DOT_PRESETS};
pub use doq::{DoQClient, DOQ_PRESETS};
pub use ecs::ClientSubnet;
pub use forward::{ForwardRule, ForwardingEngine};
pub use ip_filter::{IpFilter, IpRule};
pub use ipcrypt::IpCrypt;
pub use ipcrypt_batch::{batch_decrypt_v4, batch_decrypt_v6, batch_encrypt_v4, batch_encrypt_v6};
pub use local_doh::LocalDoHServer;
pub use local_dot::LocalDoTServer;
pub use logger::{LoggerOptions, QueryLogEntry, QueryLogger, QueryStatus};
pub use metrics_server::MetricsServer;
pub use multipath::{MultipathChannel, MultipathCoordinator};
pub use netmon::NetworkMonitor;
pub use netprobe::wait_for_network;
pub use noise::{initiate_noise_ikpsk2, NoiseSession, SymmetricState};
pub use odoh::{ODoHClient, DEFAULT_ODOH_RELAY, DEFAULT_ODOH_TARGET};
pub use pattern::{PatternMatcher, PatternRule};
pub use quic_migration::{ConnectionId, QuicMigrationController, QuicPath};
pub use schedule::{ScheduleConfig, ScheduleManager};
pub use safesearch::{SafeSearchEngine, SafeSearchOverride, YouTubeMode};
pub use secure_mem::{lock_memory, unlock_memory, SecureKey};
pub use server::DnsServer;
pub use simd_crypto::{vectorized_batch_encrypt_v4, vectorized_batch_encrypt_v6, vectorized_bulk_xor, VectorLevel};
pub use sources::{
    parse_resolver_markdown, MinisignPublicKey, RemoteResolverEntry, ServerFilterOptions, SourceConfig, SourceManager,
};
pub use sphinx::{NextAction, SphinxHop, SphinxPacket, SPHINX_PAYLOAD_SIZE, SPHINX_ROUTING_INFO_SIZE};
pub use ssrf::{is_ssrf_risk, is_ssrf_risk_ip};
pub use stamp::{DnsStamp, StampProtocol};
pub use stats::{DnsStats, DnsStatsSnapshot};
pub use stego::{decode_http_cookie, decode_ntp_carrier, encode_http_cookie, encode_ntp_carrier, StegoCarrier};
pub use system::{cleanup_system_dns, get_systemd_sockets, restore_system_dns, set_system_dns, SystemdSockets};
pub use tcp::DnsTcpServer;
pub use tls_auth::TlsClientAuth;
pub use udp_pool::UdpConnPool;
pub use watcher::FileWatcher;
pub use web_ui::WebUiServer;
pub use zkp_auth::{ZkpProof, ZkpProver, ZkpVerifier};
